### ISSUE TITLE
failing nightly tests of cmdv-test-runner due to test output getting written to error.log instead of screen

### ISSUE THREAD

**Issue by ikalash** [ACME-Climate/CMDV-testing#20]
The nightly cmdv-test-runner CDash tests I set up are failing due to changes to cmdv-test-runner that made the output be written to error.log instead of the screen: 

https://my.cdash.org/testDetails.php?test=46129640&build=1625679 

I am attaching a sample log file.  One can see that all the tests passed from the output: 
```
Ran 4 tests in 0.001s
OK
```
I can change my testing scripts to look in error.log instead of the console output for the string indicating the self-testing of cmdv-test-runner was successful, but it seems to not make sense for output from a successful run to go in an error log file.  
[error.log](https://github.com/E3SM-Project/CMDV-testing/files/3001045/error.log)

**Comment by wilke** [comment]
Changing the code to reporting library, which will return better-formatted output and status. This will fix the issue.
